"""initial

Revision ID: 832c2d6760a6
Revises:
Create Date: 2026-04-26 17:27:13.068744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "832c2d6760a6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column(
            "building_type",
            sa.Enum("RESIDENTIAL", "INDUSTRIAL", name="building_type_enum"),
            nullable=False,
        ),
        sa.Column("total_area", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("building_id", name=op.f("pk_buildings")),
    )
    op.create_table(
        "energy_balances",
        sa.Column("balance_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("loss_kwh", sa.Float(), nullable=False),
        sa.Column("loss_percent", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.building_id"],
            name=op.f("fk_energy_balances_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("balance_id", name=op.f("pk_energy_balances")),
    )
    op.create_table(
        "units",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("building_id", sa.Uuid(), nullable=False),
        sa.Column("unit_number", sa.String(length=50), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("owner_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.building_id"],
            name=op.f("fk_units_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("unit_id", name=op.f("pk_units")),
    )
    op.create_table(
        "sensors",
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("calibration_date", sa.Date(), nullable=False),
        sa.Column(
            "sensor_type",
            sa.Enum("COMMON", "INDIVIDUAL", name="sensor_type_enum"),
            nullable=False,
        ),
        sa.Column("building_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["buildings.building_id"],
            name=op.f("fk_sensors_building_id_buildings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.unit_id"],
            name=op.f("fk_sensors_unit_id_units"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("sensor_id", name=op.f("pk_sensors")),
        sa.UniqueConstraint("serial_number", name=op.f("uq_sensors_serial_number")),
    )
    op.create_table(
        "average_loads",
        sa.Column("avg_load_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "window_size",
            sa.Enum("HOUR", "DAY", name="window_size_enum"),
            nullable=False,
        ),
        sa.Column("mean_value", sa.Float(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
            name=op.f("fk_average_loads_sensor_id_sensors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("avg_load_id", name=op.f("pk_average_loads")),
    )
    op.create_table(
        "metrics",
        sa.Column("metric_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("measurement_unit", sa.String(length=10), nullable=False),
        sa.Column("voltage", sa.Float(), nullable=False),
        sa.Column("current", sa.Float(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
            name=op.f("fk_metrics_sensor_id_sensors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("metric_id", name=op.f("pk_metrics")),
    )
    op.create_table(
        "peak_loads",
        sa.Column("peak_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("max_value", sa.Float(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
            name=op.f("fk_peak_loads_sensor_id_sensors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("peak_id", name=op.f("pk_peak_loads")),
    )
    op.create_table(
        "thresholds",
        sa.Column("threshold_id", sa.Uuid(), nullable=False),
        sa.Column("sensor_id", sa.Uuid(), nullable=False),
        sa.Column("limit_value", sa.Float(), nullable=False),
        sa.Column(
            "threshold_type",
            sa.Enum("UPPER", "LOWER", name="threshold_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "tariff_zone",
            sa.Enum("DAY", "NIGHT", name="tariff_zone_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.sensor_id"],
            name=op.f("fk_thresholds_sensor_id_sensors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("threshold_id", name=op.f("pk_thresholds")),
    )
    op.create_table(
        "incidents",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column(
            "incident_type",
            sa.Enum("OVERLOAD", "LEAK", "IDLE", name="incident_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum("LOW", "HIGH", name="incident_severity_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "RESOLVED", name="incident_status_enum"),
            nullable=False,
        ),
        sa.Column("threshold_id", sa.Uuid(), nullable=True),
        sa.Column("peak_load_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["peak_load_id"],
            ["peak_loads.peak_id"],
            name=op.f("fk_incidents_peak_load_id_peak_loads"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["threshold_id"],
            ["thresholds.threshold_id"],
            name=op.f("fk_incidents_threshold_id_thresholds"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_incidents")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("incidents")
    op.drop_table("thresholds")
    op.drop_table("peak_loads")
    op.drop_table("metrics")
    op.drop_table("average_loads")
    op.drop_table("sensors")
    op.drop_table("units")
    op.drop_table("energy_balances")
    op.drop_table("buildings")
    # ### end Alembic commands ###
