from application.auth.enums import PermissionsEnum
from domain.users.enums import RoleEnum

_SUPER = {
    PermissionsEnum.CAN_CREATE_ROLE,
    PermissionsEnum.CAN_UPDATE_ROLE,
    PermissionsEnum.CAN_DELETE_ROLE,
    PermissionsEnum.CAN_READ_ROLE,
    PermissionsEnum.CAN_CREATE_ORGANIZATION,
    PermissionsEnum.CAN_READ_ORGANIZATION,
    PermissionsEnum.CAN_UPDATE_ORGANIZATION,
    PermissionsEnum.CAN_DELETE_ORGANIZATION,
    PermissionsEnum.CAN_CREATE_BUILDING,
    PermissionsEnum.CAN_READ_BUILDING,
    PermissionsEnum.CAN_UPDATE_BUILDING,
    PermissionsEnum.CAN_DELETE_BUILDING,
    PermissionsEnum.CAN_CREATE_UNIT,
    PermissionsEnum.CAN_READ_UNIT,
    PermissionsEnum.CAN_UPDATE_UNIT,
    PermissionsEnum.CAN_DELETE_UNIT,
    PermissionsEnum.CAN_CREATE_SENSOR,
    PermissionsEnum.CAN_READ_SENSOR,
    PermissionsEnum.CAN_UPDATE_SENSOR,
    PermissionsEnum.CAN_DELETE_SENSOR,
    PermissionsEnum.CAN_CREATE_THRESHOLD,
    PermissionsEnum.CAN_READ_THRESHOLD,
    PermissionsEnum.CAN_UPDATE_THRESHOLD,
    PermissionsEnum.CAN_DELETE_THRESHOLD,
    PermissionsEnum.CAN_READ_ENERGY_BALANCE,
}

_ORG_OWNER = {
    PermissionsEnum.CAN_READ_ORGANIZATION,
    PermissionsEnum.CAN_UPDATE_ORGANIZATION,
    PermissionsEnum.CAN_DELETE_ORGANIZATION,
    PermissionsEnum.CAN_CREATE_BUILDING,
    PermissionsEnum.CAN_READ_BUILDING,
    PermissionsEnum.CAN_UPDATE_BUILDING,
    PermissionsEnum.CAN_DELETE_BUILDING,
    PermissionsEnum.CAN_CREATE_UNIT,
    PermissionsEnum.CAN_READ_UNIT,
    PermissionsEnum.CAN_UPDATE_UNIT,
    PermissionsEnum.CAN_DELETE_UNIT,
    PermissionsEnum.CAN_CREATE_SENSOR,
    PermissionsEnum.CAN_READ_SENSOR,
    PermissionsEnum.CAN_UPDATE_SENSOR,
    PermissionsEnum.CAN_DELETE_SENSOR,
    PermissionsEnum.CAN_CREATE_THRESHOLD,
    PermissionsEnum.CAN_READ_THRESHOLD,
    PermissionsEnum.CAN_UPDATE_THRESHOLD,
    PermissionsEnum.CAN_DELETE_THRESHOLD,
    PermissionsEnum.CAN_READ_ENERGY_BALANCE,
}

ROLE_PERMISSIONS: dict[RoleEnum, set[PermissionsEnum]] = {
    RoleEnum.SUPER_USER: _SUPER,
    RoleEnum.SUPER_OWNER: _SUPER,
    RoleEnum.SUPER_ADMIN: _SUPER,
    RoleEnum.SUPER_REDACTOR: _SUPER,
    RoleEnum.ORGANIZATION_OWNER: _ORG_OWNER,
    RoleEnum.ADMIN: {
        PermissionsEnum.CAN_CREATE_BUILDING,
        PermissionsEnum.CAN_READ_BUILDING,
        PermissionsEnum.CAN_UPDATE_BUILDING,
        PermissionsEnum.CAN_DELETE_BUILDING,
        PermissionsEnum.CAN_CREATE_UNIT,
        PermissionsEnum.CAN_READ_UNIT,
        PermissionsEnum.CAN_UPDATE_UNIT,
        PermissionsEnum.CAN_DELETE_UNIT,
        PermissionsEnum.CAN_CREATE_SENSOR,
        PermissionsEnum.CAN_READ_SENSOR,
        PermissionsEnum.CAN_UPDATE_SENSOR,
        PermissionsEnum.CAN_DELETE_SENSOR,
        PermissionsEnum.CAN_CREATE_THRESHOLD,
        PermissionsEnum.CAN_READ_THRESHOLD,
        PermissionsEnum.CAN_UPDATE_THRESHOLD,
        PermissionsEnum.CAN_DELETE_THRESHOLD,
        PermissionsEnum.CAN_READ_ENERGY_BALANCE,
    },
    RoleEnum.REDACTOR: {
        PermissionsEnum.CAN_READ_BUILDING,
        PermissionsEnum.CAN_READ_UNIT,
        PermissionsEnum.CAN_READ_SENSOR,
        PermissionsEnum.CAN_CREATE_THRESHOLD,
        PermissionsEnum.CAN_READ_THRESHOLD,
        PermissionsEnum.CAN_UPDATE_THRESHOLD,
        PermissionsEnum.CAN_DELETE_THRESHOLD,
        PermissionsEnum.CAN_READ_ENERGY_BALANCE,
    },
    RoleEnum.OWNER: {
        PermissionsEnum.CAN_READ_BUILDING,
        PermissionsEnum.CAN_READ_UNIT,
        PermissionsEnum.CAN_READ_SENSOR,
        PermissionsEnum.CAN_READ_THRESHOLD,
        PermissionsEnum.CAN_READ_ENERGY_BALANCE,
    },
    RoleEnum.PUBLIC: set(),
}
