from enum import Enum


class PermissionsEnum(Enum):
    # Role management
    CAN_CREATE_ROLE = "CAN_CREATE_ROLE"
    CAN_UPDATE_ROLE = "CAN_UPDATE_ROLE"
    CAN_DELETE_ROLE = "CAN_DELETE_ROLE"
    CAN_READ_ROLE = "CAN_READ_ROLE"

    # Building
    CAN_CREATE_BUILDING = "CAN_CREATE_BUILDING"
    CAN_READ_BUILDING = "CAN_READ_BUILDING"
    CAN_UPDATE_BUILDING = "CAN_UPDATE_BUILDING"
    CAN_DELETE_BUILDING = "CAN_DELETE_BUILDING"

    # Unit
    CAN_CREATE_UNIT = "CAN_CREATE_UNIT"
    CAN_READ_UNIT = "CAN_READ_UNIT"
    CAN_UPDATE_UNIT = "CAN_UPDATE_UNIT"
    CAN_DELETE_UNIT = "CAN_DELETE_UNIT"

    # Sensor
    CAN_CREATE_SENSOR = "CAN_CREATE_SENSOR"
    CAN_READ_SENSOR = "CAN_READ_SENSOR"
    CAN_UPDATE_SENSOR = "CAN_UPDATE_SENSOR"
    CAN_DELETE_SENSOR = "CAN_DELETE_SENSOR"

    # Threshold
    CAN_CREATE_THRESHOLD = "CAN_CREATE_THRESHOLD"
    CAN_READ_THRESHOLD = "CAN_READ_THRESHOLD"
    CAN_UPDATE_THRESHOLD = "CAN_UPDATE_THRESHOLD"
    CAN_DELETE_THRESHOLD = "CAN_DELETE_THRESHOLD"

    # Organization
    CAN_CREATE_ORGANIZATION = "CAN_CREATE_ORGANIZATION"
    CAN_READ_ORGANIZATION = "CAN_READ_ORGANIZATION"
    CAN_UPDATE_ORGANIZATION = "CAN_UPDATE_ORGANIZATION"
    CAN_DELETE_ORGANIZATION = "CAN_DELETE_ORGANIZATION"

    # Energy balance (analytics)
    CAN_READ_ENERGY_BALANCE = "CAN_READ_ENERGY_BALANCE"
